/* vi: set ts=4 expandtab shiftwidth=4: */

/**
 * @file
 *
 * Copyright 2020 Digital Aggregates Corporation, Colorado, USA<BR>
 * Licensed under the terms in README.h<BR>
 * Chip Overclock (coverclock@diag.com)<BR>
 * https://github.com/coverclock/com-diag-placer<BR>
 * N.B. THIS HEADER FILE CAN BE INCLUDED MORE THAN ONCE.
 */

#if defined(COM_DIAG_PLACER_SCHEMA_BEGIN)
#undef COM_DIAG_PLACER_SCHEMA_BEGIN
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_BLOB)
#undef COM_DIAG_PLACER_SCHEMA_BLOB
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_BLOB_LAST)
#undef COM_DIAG_PLACER_SCHEMA_BLOB_LAST
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_FLOAT)
#undef COM_DIAG_PLACER_SCHEMA_FLOAT
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_FLOAT_LAST)
#undef COM_DIAG_PLACER_SCHEMA_FLOAT_LAST
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_INTEGER)
#undef COM_DIAG_PLACER_SCHEMA_INTEGER
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_INTEGER_LAST)
#undef COM_DIAG_PLACER_SCHEMA_INTEGER_LAST
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_INTEGER64)
#undef COM_DIAG_PLACER_SCHEMA_INTEGER64
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_INTEGER64_LAST)
#undef COM_DIAG_PLACER_SCHEMA_INTEGER64_LAST
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_TEXT)
#undef COM_DIAG_PLACER_SCHEMA_TEXT
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_TEXT_LAST)
#undef COM_DIAG_PLACER_SCHEMA_TEXT_LAST
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_TEXT16)
#undef COM_DIAG_PLACER_SCHEMA_TEXT16
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_TEXT16_LAST)
#undef COM_DIAG_PLACER_SCHEMA_TEXT16_LAST
#endif

#if defined(COM_DIAG_PLACER_SCHEMA_END)
#undef COM_DIAG_PLACER_SCHEMA_END
#endif
