/* vi: set ts=4 expandtab shiftwidth=4: */
/**
 * @file
 *
 * Copyright 2020 Digital Aggregates Corporation, Colorado, USA<BR>
 * Licensed under the terms in LICENSE.txt<BR>
 * Chip Overclock <coverclock@diag.com><BR>
 * https://github.com/coverclock/com-diag-placer<BR>
 */

#include "com/diag/diminuto/diminuto_unittest.h"
#include "com/diag/placer/placer_sql.h"
#include <stdio.h>
#include <string.h>

#define ERRORTEST(_NUMBER_) \
    { \
        int number = _NUMBER_; \
        const char * name = (const char *)0; \
        const char * message = (const char *)0; \
        name = #_NUMBER_; \
        message = sqlite3_errstr(number); \
        COMMENT("name=\"%s\" number=%d message=\"%s\"\n", name, number, message ? message : ""); \
        placer_sql_error(_NUMBER_); \
    }

int main(void)
{
    SETLOGMASK();

    {
        ERRORTEST(SQLITE_OK);
        ERRORTEST(SQLITE_ERROR);
        ERRORTEST(SQLITE_INTERNAL);
        ERRORTEST(SQLITE_PERM);
        ERRORTEST(SQLITE_ABORT);
        ERRORTEST(SQLITE_BUSY);
        ERRORTEST(SQLITE_LOCKED);
        ERRORTEST(SQLITE_NOMEM);
        ERRORTEST(SQLITE_READONLY);
        ERRORTEST(SQLITE_INTERRUPT);
        ERRORTEST(SQLITE_IOERR);
        ERRORTEST(SQLITE_CORRUPT);
        ERRORTEST(SQLITE_NOTFOUND);
        ERRORTEST(SQLITE_FULL);
        ERRORTEST(SQLITE_CANTOPEN);
        ERRORTEST(SQLITE_PROTOCOL);
        ERRORTEST(SQLITE_EMPTY);
        ERRORTEST(SQLITE_SCHEMA);
        ERRORTEST(SQLITE_TOOBIG);
        ERRORTEST(SQLITE_CONSTRAINT);
        ERRORTEST(SQLITE_MISMATCH);
        ERRORTEST(SQLITE_MISUSE);
        ERRORTEST(SQLITE_NOLFS);
        ERRORTEST(SQLITE_AUTH);
        ERRORTEST(SQLITE_FORMAT);
        ERRORTEST(SQLITE_RANGE);
        ERRORTEST(SQLITE_NOTADB);
        ERRORTEST(SQLITE_NOTICE);
        ERRORTEST(SQLITE_WARNING);
        ERRORTEST(SQLITE_ROW);
        ERRORTEST(SQLITE_DONE);
    }

    {
        ERRORTEST(SQLITE_ERROR_MISSING_COLLSEQ);
        ERRORTEST(SQLITE_ERROR_RETRY);
        ERRORTEST(SQLITE_ERROR_SNAPSHOT);
        ERRORTEST(SQLITE_IOERR_READ);
        ERRORTEST(SQLITE_IOERR_SHORT_READ);
        ERRORTEST(SQLITE_IOERR_WRITE);
        ERRORTEST(SQLITE_IOERR_FSYNC);
        ERRORTEST(SQLITE_IOERR_DIR_FSYNC);
        ERRORTEST(SQLITE_IOERR_TRUNCATE);
        ERRORTEST(SQLITE_IOERR_FSTAT);
        ERRORTEST(SQLITE_IOERR_UNLOCK);
        ERRORTEST(SQLITE_IOERR_RDLOCK);
        ERRORTEST(SQLITE_IOERR_DELETE);
        ERRORTEST(SQLITE_IOERR_BLOCKED);
        ERRORTEST(SQLITE_IOERR_NOMEM);
        ERRORTEST(SQLITE_IOERR_ACCESS);
        ERRORTEST(SQLITE_IOERR_CHECKRESERVEDLOCK);
        ERRORTEST(SQLITE_IOERR_LOCK);
        ERRORTEST(SQLITE_IOERR_CLOSE);
        ERRORTEST(SQLITE_IOERR_DIR_CLOSE);
        ERRORTEST(SQLITE_IOERR_SHMOPEN);
        ERRORTEST(SQLITE_IOERR_SHMSIZE);
        ERRORTEST(SQLITE_IOERR_SHMLOCK);
        ERRORTEST(SQLITE_IOERR_SHMMAP);
        ERRORTEST(SQLITE_IOERR_SEEK);
        ERRORTEST(SQLITE_IOERR_DELETE_NOENT);
        ERRORTEST(SQLITE_IOERR_MMAP);
        ERRORTEST(SQLITE_IOERR_GETTEMPPATH);
        ERRORTEST(SQLITE_IOERR_CONVPATH);
        ERRORTEST(SQLITE_IOERR_VNODE);
        ERRORTEST(SQLITE_IOERR_AUTH);
        ERRORTEST(SQLITE_IOERR_BEGIN_ATOMIC);
        ERRORTEST(SQLITE_IOERR_COMMIT_ATOMIC);
        ERRORTEST(SQLITE_IOERR_ROLLBACK_ATOMIC);
        ERRORTEST(SQLITE_LOCKED_SHAREDCACHE);
        ERRORTEST(SQLITE_LOCKED_VTAB);
        ERRORTEST(SQLITE_BUSY_RECOVERY);
        ERRORTEST(SQLITE_BUSY_SNAPSHOT);
        ERRORTEST(SQLITE_CANTOPEN_NOTEMPDIR);
        ERRORTEST(SQLITE_CANTOPEN_ISDIR);
        ERRORTEST(SQLITE_CANTOPEN_FULLPATH);
        ERRORTEST(SQLITE_CANTOPEN_CONVPATH);
        ERRORTEST(SQLITE_CANTOPEN_DIRTYWAL);
        ERRORTEST(SQLITE_CORRUPT_VTAB);
        ERRORTEST(SQLITE_CORRUPT_SEQUENCE);
        ERRORTEST(SQLITE_READONLY_RECOVERY);
        ERRORTEST(SQLITE_READONLY_CANTLOCK);
        ERRORTEST(SQLITE_READONLY_ROLLBACK);
        ERRORTEST(SQLITE_READONLY_DBMOVED);
        ERRORTEST(SQLITE_READONLY_CANTINIT);
        ERRORTEST(SQLITE_READONLY_DIRECTORY);
        ERRORTEST(SQLITE_ABORT_ROLLBACK);
        ERRORTEST(SQLITE_CONSTRAINT_CHECK);
        ERRORTEST(SQLITE_CONSTRAINT_COMMITHOOK);
        ERRORTEST(SQLITE_CONSTRAINT_FOREIGNKEY);
        ERRORTEST(SQLITE_CONSTRAINT_FUNCTION);
        ERRORTEST(SQLITE_CONSTRAINT_NOTNULL);
        ERRORTEST(SQLITE_CONSTRAINT_PRIMARYKEY);
        ERRORTEST(SQLITE_CONSTRAINT_TRIGGER);
        ERRORTEST(SQLITE_CONSTRAINT_UNIQUE);
        ERRORTEST(SQLITE_CONSTRAINT_VTAB);
        ERRORTEST(SQLITE_CONSTRAINT_ROWID);
        ERRORTEST(SQLITE_NOTICE_RECOVER_WAL);
        ERRORTEST(SQLITE_NOTICE_RECOVER_ROLLBACK);
        ERRORTEST(SQLITE_WARNING_AUTOINDEX);
        ERRORTEST(SQLITE_AUTH_USER);
        ERRORTEST(SQLITE_OK_LOAD_PERMANENTLY);
    }

    EXIT();
}

